import type { SupportedLocale } from "./preferences";

const es = {
  appName: "Yanti", tagline: "Compraventa entre particulares con protección",
  nav: { home: "Inicio", purchases: "Compras", sales: "Ventas", disputes: "Reclamos", profile: "Perfil", logout: "Salir", admin: "Consola" },
  home: { welcome: "Hola, {name}", needsAction: "Requiere tu acción", recent: "Actividad reciente", empty: "Todavía no tenés operaciones.", newSale: "Nueva solicitud", viewInbox: "Buzón (demo)", adminPanel: "Consola de operaciones" },
  status: { DRAFT: "Borrador", AWAITING_ACCEPTANCE: "Pendiente de aceptación", ACCEPTED_AWAITING_PAYMENT: "Aceptada · pendiente de pago", PAYMENT_IN_PROGRESS: "Pago en proceso", PAID_AWAITING_SHIPMENT: "Pagada · pendiente de envío", SHIPPED_AWAITING_RECEIPT: "Enviada · pendiente de confirmación", CONFIRMATION_OVERDUE: "Confirmación vencida", IN_DISPUTE: "En disputa", RETURN_REQUIRED: "Devolución requerida", RELEASE_IN_PROGRESS: "Liberación en proceso", REFUND_IN_PROGRESS: "Reembolso en proceso", COMPLETED: "Completada", REFUNDED: "Reembolsada", CANCELLED: "Cancelada", EXPIRED: "Expirada", EXCEPTION_REVIEW: "Revisión excepcional" },
  role: { BUYER: "Compraste", SELLER: "Vendiste" },
  op: { amount: "Monto del producto", buyerFee: "Comisión del comprador", sellerFee: "Comisión del vendedor", totalToPay: "Total a pagar", netToReceive: "Neto a recibir", currency: "Moneda", confirmReceipt: "Confirmar recepción", openDispute: "Abrir reclamo", declareShipment: "Declarar envío", pay: "Ir a pagar", accept: "Aceptar acuerdo", timeline: "Línea de tiempo", seller: "Vendedor", buyer: "Comprador", status: "Estado", supportCode: "Código", created: "Creada", category: "Categoría", country: "País", tracking: "Seguimiento", actions: "Acciones", noActions: "No hay acciones pendientes" },
  dispute: { reason: "Motivo", reasons: { NOT_RECEIVED: "No recibí el producto", DIFFERENT_ITEM: "Recibí un artículo distinto", DAMAGED: "El artículo llegó dañado", MISSING_PARTS: "Faltan accesorios", UNDISCLOSED_CONDITION: "Condición no declarada", OTHER: "Otro" }, describe: "Contanos qué pasó", submit: "Abrir reclamo", evidence: "Aportar evidencia", yourClaim: "Tu reclamo", otherSide: "Respuesta de la contraparte" },
  admin: { title: "Consola de operaciones", inbox: "Bandeja de disputas", audit: "Auditoría", resolve: "Resolver", propose: "Proponer resolución", confirm: "Confirmar resolución", reconcile: "Reconciliar pago", release: "Liberar al vendedor", refund: "Reembolsar al comprador", requireReturn: "Exigir devolución", rationale: "Fundamento de la resolución" },
};
export type Translations = typeof es;
const en: Translations = { ...es, tagline: "Protected person-to-person marketplace", nav: { home: "Home", purchases: "Purchases", sales: "Sales", disputes: "Disputes", profile: "Profile", logout: "Sign out", admin: "Console" }, home: { welcome: "Hello, {name}", needsAction: "Needs your action", recent: "Recent activity", empty: "You do not have any transactions yet.", newSale: "New request", viewInbox: "Inbox (demo)", adminPanel: "Operations console" }, role: { BUYER: "You bought", SELLER: "You sold" }, op: { ...es.op, amount: "Item amount", buyerFee: "Buyer fee", sellerFee: "Seller fee", totalToPay: "Total to pay", netToReceive: "Net to receive", currency: "Currency", confirmReceipt: "Confirm receipt", openDispute: "Open dispute", declareShipment: "Declare shipment", pay: "Go to payment", accept: "Accept agreement", timeline: "Timeline", seller: "Seller", buyer: "Buyer", status: "Status", supportCode: "Code", created: "Created", category: "Category", country: "Country", tracking: "Tracking", actions: "Actions", noActions: "No pending actions" }, dispute: { ...es.dispute, reason: "Reason", describe: "Tell us what happened", submit: "Open dispute", evidence: "Provide evidence", yourClaim: "Your claim", otherSide: "Other party's response" }, admin: { ...es.admin, title: "Operations console", inbox: "Dispute inbox", audit: "Audit", resolve: "Resolve", propose: "Propose resolution", confirm: "Confirm resolution", reconcile: "Reconcile payment", release: "Release to seller", refund: "Refund buyer", requireReturn: "Require return", rationale: "Resolution rationale" } };
const pt: Translations = { ...es, tagline: "Compra e venda protegida entre pessoas", nav: { home: "Início", purchases: "Compras", sales: "Vendas", disputes: "Reclamações", profile: "Perfil", logout: "Sair", admin: "Console" }, home: { welcome: "Olá, {name}", needsAction: "Requer sua ação", recent: "Atividade recente", empty: "Você ainda não tem operações.", newSale: "Nova solicitação", viewInbox: "Caixa de entrada (demo)", adminPanel: "Console de operações" }, role: { BUYER: "Você comprou", SELLER: "Você vendeu" } };
const fr: Translations = { ...es, tagline: "Achat-vente entre particuliers protégée", nav: { home: "Accueil", purchases: "Achats", sales: "Ventes", disputes: "Réclamations", profile: "Profil", logout: "Se déconnecter", admin: "Console" }, home: { welcome: "Bonjour, {name}", needsAction: "Votre action est requise", recent: "Activité récente", empty: "Vous n'avez pas encore d'opérations.", newSale: "Nouvelle demande", viewInbox: "Boîte de réception (démo)", adminPanel: "Console des opérations" }, role: { BUYER: "Vous avez acheté", SELLER: "Vous avez vendu" } };
export const translations: Record<SupportedLocale, Translations> = { es, en, pt, fr };
export function getTranslations(locale: SupportedLocale = "es"): Translations { return translations[locale] ?? es; }
export const t = es;
